### ISSUE TITLE
Expanding to interface builder samples

### ISSUE THREAD

**Issue by LoetLuemmel** [wigging/swift-macos#12]
Congrats, this side is great and exactly what I am looking for, working with Swift and macOS!

Suggestion: I try to find samples to understand the 'rubber band' functionality used in conjunction with e.g.:  @IBAction func related to radio buttons.

Well, it is a personal challenge I am having right now: Four text fields should be evaluated by its content. In order to calculate mathematical results, the <calculate> button should be deactivated, till all inputs are valid or at least meaningful.
If all four text fields are filled accordingly, the <calculate>-button should become activated.

Maybe you could provide me a hint where to start and I would try to submit this course with a pull request?

Happy hackin'
LoetLuemmel!

**Comment by wigging** [comment]
Is there a particular reason why you want to use Interface Builder? Why not use SwiftUI? I haven't used Interface Builder in a long time and I have honestly forgotten most of it.

**Comment by LoetLuemmel** [comment]
I didn't know, that SwiftUI is cross platform capable for AppleOS devices and could check how this works with SwiftUI.

Interface Builder is nice for quick prototypes, but can become very tricky. At the end of the story, IB is a XML blackbox.

**Comment by wigging** [comment]
SwiftUI is quickly becoming the way to develop apps for all of Apple's platforms. I strongly suggest using SwiftUI if you're getting started with app development. It's good to be familiar with AppKit and Interface Builder but the future of app development is SwiftUI.

**Comment by LoetLuemmel** [comment]
Nothing to be added!    : )

**Comment by wigging** [comment]
Thank you for the suggestion. But I would like to keep the examples in SwiftUI.
