### ISSUE TITLE
Suggestion: Preference window

### ISSUE THREAD

**Issue by kicsipixel** [wigging/swift-macos#6]
Tutorial about how to add Preference window to a  SwiftUI macOS app.

**Comment by wigging** [comment]
A preferences window example definitely needs to be a part of this repo. Please submit an example and name the Xcode project PreferencesWindow.

**Comment by wigging** [comment]
I'm going to update the contribution guidelines and add a gitignore file for the repository. Please wait until I have made those updates before submitting a preference window example.

**Comment by wigging** [comment]
I added a gitignore file to the repo. Make sure you pull down the latest version before making any more pull requests. Thanks again for your contributions.

**Comment by kicsipixel** [comment]
The Preference window example can be based on your AppStorage as we need somewhere to store the settings.

**Comment by wigging** [comment]
Apple has a basic example at https://developer.apple.com/documentation/swiftui/settings. Looks like a good place to start.
