### ISSUE TITLE
Suggestion: Showing macOS version availability

### ISSUE THREAD

**Issue by kicsipixel** [wigging/swift-macos#9]
New SwiftUI features are coming, some of them are supported only on the latest macOS .e.g. [Table](https://developer.apple.com/documentation/swiftui/table). It might be worth considering to introduce some kind of "flag/badge" which would shows where that feature is available.

**Comment by wigging** [comment]
My goal is to keep the website and example code up-to-date with the latest released versions of Swift and SwiftUI. I know there are new features available in the beta versions but those can be added to the website once they are officially released.

**Comment by wigging** [comment]
Xcode 13 is available but still waiting on macOS 12 to be released.

**Comment by wigging** [comment]
I added some Table examples to the repository which is a latest macOS feature. Otherwise, I don't plan to add any badges/flags to the site.
